general_settings:
  recordlengths: 2000 #samples [4, 10485760]
  pretriggers: 500 # samples [0, 2042]
  software_trigger_rate: 100 # Hz
  max_file_size_mb: 100
  buffer_size: 50
  interval_stats: 2000
  iolevel: TTL
  acqtriggersource: ITLA
  busyinsource: SIN
  entriggeroverlap: False
  itlaenretrigger: False
  itlagatewidth: 0
  itlamainlogic: OR
  itlamajoritylev: 1
  itlamask: 0x003
  itlapairlogic: NONE
  itlapolarity: Direct
  startsource: SWcmd
channel_settings:
  group1:
    channels: "0..1"
    chenable: True
    chsupprsamplesoverthreshold: 1
    chsupprthr: 0
    dcoffset: 10
    itlconnect: ITLA
    overthresholdvetowidth: 0
    samplesoverthreshold: 1
    selftriggeredge: RISE
    selftriggerwidth: 2
    signaloffset: 0
    triggerthr: 500
    triggerthrmode: Relative